# Custom composite action
# SEE:
# - https://docs.github.com/en/actions/concepts/workflows-and-actions/custom-actions 
# - https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax

name: 'Get & Cache Dependencies'
description: 'Composite Action: Get the dependencies (via npm) and cache them.' # show in GitHub Marketplace
inputs:
  caching:
    description: 'Whether to cache dependencies or not.'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache was used.'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite' # this is a custom composite action
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
      shell: bash # have to specify shell when using 'run' in a Composite Action